# AUTOGENERATED FROM 'app/queries/getNumberOfClients.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import edgedb
import uuid


async def getNumberOfClients(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> int:
    return await executor.query_single(
        """\
        with clients := (select User.client filter .id = <uuid>$user_id)
        select count(clients)\
        """,
        user_id=user_id,
    )
