# AUTOGENERATED FROM 'app/queries/getNumberOfActiveServices.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import edgedb
import uuid


async def getNumberOfActiveServices(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> int:
    return await executor.query_single(
        """\
        with services := (select User.service filter .id = <uuid>$user_id),
        active := (select services filter .status = false )
        select count(active)\
        """,
        user_id=user_id,
    )
