# AUTOGENERATED FROM 'app/queries/getClient.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class getClientResult(NoPydanticValidation):
    id: uuid.UUID
    email: str
    name: str | None
    govt_id: str | None
    sex: str | None
    relationship: str | None
    details: str | None
    type_client: str | None
    birth: datetime.datetime | None
    city: str | None
    state: str | None
    phone: list[str] | None
    address: list[str] | None
    custom_fields: list[str] | None


async def getClient(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> getClientResult | None:
    return await executor.query_single(
        """\
        select Client {
            id,
            email,
            name,
            govt_id,
            sex,
            relationship,
            details,
            type_client,
            birth,
            city,
            state,
            phone,
            address,
            custom_fields
        } filter .id = <uuid>$id;\
        """,
        id=id,
    )
