# AUTOGENERATED FROM 'app/queries/unit/createUnit.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class createUnitResult(NoPydanticValidation):
    id: uuid.UUID


async def createUnit(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
    email: str,
    name: str,
    template_model: str,
    relationship: str,
    govt_id: str,
    sex: str,
    details: str,
    type_unit: str,
    birth: datetime.date,
    custom_fields: str,
    phoneNumber: str,
    contact: str,
    phoneComplement: str,
    state: str,
    city: str,
    district: str,
    street: str,
    addressNumber: int,
    addressComplement: str,
    postal: str,
) -> createUnitResult:
    return await executor.query_single(
        """\
        insert Unit {
            user := <User><uuid>$user_id,
            email := <str>$email,
            name := <str>$name,
            template_model := <str>$template_model,
            relationship := <str>$relationship,
            govt_id := <str>$govt_id,
            sex := <str>$sex,
            details := <str>$details,
            type_unit := <str>$type_unit,
            birth := <cal::local_date>$birth,
            custom_fields := <json>$custom_fields,
            phone := (
                insert Contact {
                    number := <str>$phoneNumber,
                    contact := <str>$contact,
                    complement := <str>$phoneComplement
                }
            ),
            address := (
                insert Address {
                    state := <str>$state,
                    city := <str>$city,
                    district := <str>$district,
                    street := <str>$street,
                    number := <int16>$addressNumber,
                    complement := <str>$addressComplement,
                    postal := <str>$postal
                }
            )
        }\
        """,
        user_id=user_id,
        email=email,
        name=name,
        template_model=template_model,
        relationship=relationship,
        govt_id=govt_id,
        sex=sex,
        details=details,
        type_unit=type_unit,
        birth=birth,
        custom_fields=custom_fields,
        phoneNumber=phoneNumber,
        contact=contact,
        phoneComplement=phoneComplement,
        state=state,
        city=city,
        district=district,
        street=street,
        addressNumber=addressNumber,
        addressComplement=addressComplement,
        postal=postal,
    )
