# AUTOGENERATED FROM 'app/queries/unit/deleteAddress.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class deleteAddressResult(NoPydanticValidation):
    id: uuid.UUID


async def deleteAddress(
    executor: edgedb.AsyncIOExecutor,
    *,
    address_id: uuid.UUID,
) -> deleteAddressResult | None:
    return await executor.query_single(
        """\
        delete Address filter .id = <uuid>$address_id\
        """,
        address_id=address_id,
    )
