# AUTOGENERATED FROM 'app/queries/unit/deleteUnit.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class deleteUnitResult(NoPydanticValidation):
    id: uuid.UUID


async def deleteUnit(
    executor: edgedb.AsyncIOExecutor,
    *,
    unit_id: uuid.UUID,
) -> list[deleteUnitResult]:
    return await executor.query(
        """\
        for i in {
            (select Contact filter .id = <uuid>$unit_id),
            (select Address filter .id = <uuid>$unit_id),
            (select Unit filter .id = <uuid>$unit_id)
        }
        delete i;\
        """,
        unit_id=unit_id,
    )
