# AUTOGENERATED FROM 'app/queries/createClient.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class createClientResult(NoPydanticValidation):
    id: uuid.UUID


async def createClient(
    executor: edgedb.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
    email: str,
    name: str,
    template_model: str,
    relationship: str,
    govt_id: str,
    sex: str,
    details: str,
    type_client: str,
    birth: datetime.datetime,
    custom_fields: list[str],
) -> createClientResult:
    return await executor.query_single(
        """\
        insert Client {
            user := <User><uuid>$user_id,
            email := <str>$email,
            name := <str>$name,
            template_model := <str>$template_model,
            relationship := <str>$relationship,
            govt_id := <str>$govt_id,
            sex := <str>$sex,
            details := <str>$details,
            type_client := <str>$type_client,
            birth := <datetime>$birth,
            custom_fields := <array<json>>$custom_fields
        }\
        """,
        user_id=user_id,
        email=email,
        name=name,
        template_model=template_model,
        relationship=relationship,
        govt_id=govt_id,
        sex=sex,
        details=details,
        type_client=type_client,
        birth=birth,
        custom_fields=custom_fields,
    )
