# AUTOGENERATED FROM 'app/queries/auth/getUser.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class getUserResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    email: str


async def getUser(
    executor: edgedb.AsyncIOExecutor,
) -> getUserResult | None:
    return await executor.query_single(
        """\
        select User {
            name,
            email
        } limit 1;\
        """,
    )
